### ISSUE TITLE
fast enough fastpipes?

### ISSUE THREAD

**Issue by santiagorr** [libmoon/libmoon#14]
Hi,

I am working on a script to count and analyse packets by frequency sketchs. As you can see in the attached simplified script [rx-count-pipe.lua.txt](https://github.com/libmoon/libmoon/files/533561/rx-count-pipe.lua.txt) (based on rx-pkts-distribution.lua), the sketchUpdate function holds a counter according to the data that it receives from counterSlave via a fast pipe. I am having some trouble to count with the "sketch" function a similar amount of packets than counterSlave. After sending ~100M packets from a generator at  10Gbps rate, I am having results like this (~20M from those 100M):

    ^C[Device: id=0] RX: 6.25 (StdDev 5.85) Mpps, 4200 (StdDev 3932) Mbit/s (5200 Mbit/s with framing), total 100000026 packets with 8400002184 bytes (incl. CRC)
    [Packets counted] RX: 6.25 (StdDev 5.85) Mpps, 4200 (StdDev 3932) Mbit/s (5200 Mbit/s with framing), total 100000026 packets with 8400002184 bytes (incl. CRC)
    Pipe-relying function counted: 21193438

Are the fast pipes suitable for this kind of fast intertask communication, without "losing" packets?

Cheers, and thanks for this great framework!

Santiago

**Comment by emmericp** [comment]
Pipes should be fast enough for something like this. Also, they are unbounded queues, i.e., will never lose data, you will see packet loss on the NIC if you overload this.

However, your code is incorrect as you are re-using the same buffer without checking if it was already accounted for by the rx thread. You'd need a pool of buffers and a second pipe send used buffers back to the rx thread.
Depending on what you are trying to achieve, I'd simply mmap() a huge array and write the statistics to it; maybe double-buffer it and rotate every second or so if it's supposed to be running longer.


Also, beware of the counter:update() call if doing timing-critical stuff. The print that is triggered every second will result in a spike of latency under a high load. (A lot of software packet generators actually fail precision tests due to periodic printing of stats in the tx thread)

The "huge array" approach actually has a similar problem: there will be pagefaults that add unexpected latency. In general, it's just very hard to do anything related to timing in software.
