### ISSUE TITLE
cpu usage reduction

### ISSUE THREAD

**Issue by kullanici0606** [libmoon/libmoon#83]
Hi,

I started using libmoon and it is a great project. It captures and dumps packets without any drops. Our packets are much larger than minimum packet size, we receive approximately 1.5Mpps for 10Gbps. Therefore I wonder, if it is possible to reduce cpu usage of libmoon. Currently it uses all the cpu (i.e for 8 threads, 8 x 100% = 800% cpu usage), since it is polling all the time. There is a sample application in DPDK documentation[1] for power management. I want to use C-states (i.e sleep when possible). How can I achieve that when using dump-pkts.lua (https://github.com/libmoon/libmoon/blob/master/examples/dump-pkts.lua)?

Dump-pkts uses tryRecv with 100 microseconds
https://github.com/libmoon/libmoon/blob/455db223838c3bc3ca3edcf5e98c44df6c8bf252/examples/dump-pkts.lua#L80

And it seems that tryRecv method sleeps for 1 micro seconds for every loop:

https://github.com/libmoon/libmoon/blob/e9a933b862888825f6294eb1b05ab2464cd8d789/lua/device.lua#L860-L875

Is 1 micro seconds not enough in order to reduce CPU usage? Should I change the libmoon code to something higher or is there any other way to achive that? Could you please help me or point me the right direction?

[1] http://doc.dpdk.org/guides/sample_app_ug/l3_forward_power_man.html

**Comment by emmericp** [comment]
Reducing CPU usage for high-speed networking is a really hard problem if you also want to keep your latency low. (insert longer ramble about NAPI and interrupt throttling here which doesn't work the way most people think it works)

But as a quick and dirty implementation similar to what the linked code does: try libmoon.sleepMicrosIdle() instead of libmoon.sleepMicros(). We always default to busy sleep because power-saving is a non-goal for this project at the moment: we want to prototype stuff.
