### ISSUE TITLE
Additional packet types

### ISSUE THREAD

**Issue by kabaka0** [libmoon/libmoon#84]
Would you be able to add constructors for ethernet vlan packets with udp and/or tcp fields built in? It is straightforward to do ( for example, in my case, I directly edited packet.lua to add a vlan field to getUdpPacket), is there any reason why you opted not to given how many different options you built in? Can do a pull request if needed, but it is only a couple of lines of code.

**Comment by emmericp** [comment]
The reason why it's not delcared in the default headers is that it is rarely used; in general, offloading the vlan tags to the hardware is better because vlan tags are really annoying. This is supported by basically all NICs.
Example: https://github.com/libmoon/libmoon/blob/master/examples/reflector.lua#L60


The idea is that if you need more complex stacks, you can just define them yourself. You don't need to edit packet.lua

for example

```
require "packet"
local myVlanPkt = createStack({"eth", subType = "vlan"}, "ip6", "udp")

-- in main loop
local pkt = myVlanPkt(buf)
```

**Comment by kabaka0** [comment]
Got it. Thanks for quick response!
